sudo: required
services:
  - docker

before_install:
  - docker build -t sohan0077/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sohan0077/react-test npm run test -- --coverage

after_success:
  - docker build -t sohan0077/ano-multi-client ./client
  - docker build -t sohan0077/ano-multi-worker ./worker
  - docker build -t sohan0077/ano-multi-server ./server
  - docker build -t sohan0077/ano-multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sohan0077/ano-multi-client
  - docker push sohan0077/ano-multi-worker
  - docker push sohan0077/ano-multi-server
  - docker push sohan0077/ano-multi-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker-test
  env: Multidockertest-env
  bucket_name: elasticbeanstalk-ap-south-1-806822280125
  bucket_path: test-path
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrest_access_key:
    secure: $AWS_SECRET_KEY
